FROM node:16

WORKDIR /usr/src/app

EXPOSE 5001

COPY ./example-frontend/ .

ENV REACT_APP_BACKEND_URL=http://127.0.0.1:8080

RUN npm install
RUN npm run build
RUN npm install -g serve

CMD serve -s -l 5001 build